pipeline {
    agent { dockerfile true }
    environment {
        JPL_GITHUB_TOKEN    = credentials('JPL_GITHUB_TOKEN')
    }
    stages {
        stage('Build') {
            steps {
                echo 'Starting to build docker image'

                script {
                    def customImage = docker.build("my-image:${env.BUILD_ID}")
                }
            }
        }
    }
}
