pipeline {
    agent { dockerfile true }
    environment {
        JPL_GITHUB_TOKEN    = 'abc123'
    }
    stages {
        stage('Buildit') {
            steps {
                script {
                    def customImage = docker.build("my-image:${env.BUILD_ID}", "--build-arg JPL_GITHUB_TOKEN=bongo", "--no-cache", ".")
                }
            }
        }
    }
}
