pipeline {
    agent {
        label 'CAE-Jenkins2-DH-Agents-Linux'
    }
    stages {
        stage('Back-end') 
	{
            agent {
                docker { 
                    image 'maven:3-alpine' 
                    reuseNode true
                }
            }
            steps {
                sh 'mvn --version'
            }
        }
        stage('Front-end') {
            agent {
                docker { 
                    image 'node:7-alpine'
                    reuseNode true
                }
            }
            steps {
                sh 'node --version'
            }
        }
    }
}
