pipeline {
    agent { docker { image 'maven:3.3.3' } }

    options {
        skipStagesAfterUnstable()
    }

    environment {
        TEST_FLAG = 'true'
        JPL_GITHUB_TOKEN = credentials('JPL_GITHUB_TOKEN')
    }

    stages {
        stage('Build') {
            steps {
                echo "Build #: ${env.BUILD_NUMBER}"
                sh 'mvn --version'
            }
        }
        stage('Test - atlo') {
            environment {
              VENUE = 'atlo'
            }
            steps {
                echo "TEST_FLAG=$TEST_FLAG"
                echo "VENUE=$VENUE"
                sh 'echo "Testing 123"; exit 0'
            }
        }
        stage('Test - sbeta') {
            environment {
              VENUE = 'sbeta'
            }
            steps {
                echo "TEST_FLAG=$TEST_FLAG"
                echo "VENUE=$VENUE"
                sh 'echo "Testing 123"; exit 0'
            }
        }
        stage('Deploy') {
          steps {
                retry(2) {
                    sh 'ls -al $HOME'
                }
          }
        }
    }
    post {
        always {
            echo 'This will always run'
            deleteDir() /* clean up our workspace */
        }
        success {
            echo 'This will run only if successful'
        }
        failure {
            echo 'This will run only if failed'
        }
        unstable {
            echo 'This will run only if the run was marked as unstable'
        }
        changed {
            echo 'This will run only if the state of the Pipeline has changed'
            echo 'For example, if the Pipeline was previously failing but is now successful'
        }
    }
}
