pipeline {
    agent { docker { image 'maven:3.3.3' } }

   environment {
        TEST_FLAG = 'true'
    }

    stages {
        stage('Build') {
            steps {
                sh 'mvn --version'
            }
        }
        stage('Deploy') {
          steps {
                retry(2) {
                    sh 'ls -al $HOME'
                }
          }
        }
        stage('Test') {
            steps {
                echo "TEST_FLAG=$TEST_FLAG"
                sh 'echo "Testing 123"; exit 0'
            }
        }
    }
    post {
        always {
            echo 'This will always run'
        }
        success {
            echo 'This will run only if successful'
        }
        failure {
            echo 'This will run only if failed'
        }
        unstable {
            echo 'This will run only if the run was marked as unstable'
        }
        changed {
            echo 'This will run only if the state of the Pipeline has changed'
            echo 'For example, if the Pipeline was previously failing but is now successful'
        }
    }
}
